services:
  fastapi-server:
    container_name: fastapi-server
    image: 06f9ee171ffc
    ports:
      - "8000:8000"
    volumes:
      - ../model:/home/model
    environment:
      - MODEL_PATH=/home/model/model-ckpt.pt
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]


#>>> from ultralytics.utils.plotting import Annotator
#>>> b = [
#...     [
#...       514.2191162109375,
#...       630.6876220703125,
#...       565.9525146484375,
#...       682.3275146484375
#...     ],
#...     [
#...       0.5343818664550781,
#...       701.951904296875,
#...       59.46540451049805,
#...       795.455322265625
#...     ],
#...     [
#...       1224.9991455078125,
#...       1253.5360107421875,
#...       1245.5916748046875,
#...       1270.1756591796875
#...     ]
#...   ]
#>>> c = [
#...     0,
#...     0,
#...     0
#...   ]
#>>> annotator = Annotator("0c07917a-DJI_0536_0_1.jpg")
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "/home/neo/Documents/projs/torchflowv2/venv/lib/python3.10/site-packages/ultralytics/utils/plotting.py", line 118, in __init__
#    self.lw = line_width or max(round(sum(im.size if input_is_pil else im.shape) / 2 * 0.003), 2)
#AttributeError: 'str' object has no attribute 'shape'
#>>> annotator = Annotator("0c07917a-DJI_0536_0_1.jpg")
#KeyboardInterrupt
#>>> import cv2
#>>> annotator = Annotator(cv2.read("0c07917a-DJI_0536_0_1.jpg"))
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#AttributeError: module 'cv2' has no attribute 'read'
#>>> annotator = Annotator(cv2.imread("0c07917a-DJI_0536_0_1.jpg"))
#>>> an
#and        anext(     annotator  any(
#>>> annotator
#<ultralytics.utils.plotting.Annotator object at 0x7c4d25c1d510>
#>>> clear
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#NameError: name 'clear' is not defined
#>>> annotator.box_label(b, "plastic")
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "/home/neo/Documents/projs/torchflowv2/venv/lib/python3.10/site-packages/ultralytics/utils/plotting.py", line 189, in box_label
#    p1, p2 = (int(box[0]), int(box[1])), (int(box[2]), int(box[3]))
#TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'
#>>> annotator.box_label(b[0], "plastic")
#>>> img = annotator.result()
#>>> cv2.imshow(img)
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#cv2.error: OpenCV(4.9.0) :-1: error: (-5:Bad argument) in function 'imshow'
#> Overload resolution failed:
#>  - imshow() missing required argument 'mat' (pos 2)
#>  - imshow() missing required argument 'mat' (pos 2)
#>  - imshow() missing required argument 'mat' (pos 2)
#
#>>> cv2.imshow('', img)
#>>>
#KeyboardInterrupt
#>>> cv2.imwrite("image.jpeg", img)
#True
#>>>
#